import json, os
from django.core.management.base import BaseCommand
from django.conf import settings

from themer.settings import (
    get_themer_settings
)

class Command(BaseCommand):
    help = "Exports color palette settings defined in django conf to javascript file."
    js_file_warning = """
/**
 * Only edit this file as a last resort. It is autogenerated through django management commands.
 * Learn more about the themer management commands before attempting to edit here.
 */
""".lstrip()
    
    def handle(self, *args, **options):
        themer_path = os.path.join(
            getattr(settings, 'BASE_DIR'),
            'themer'
        )
        themer_settings = get_themer_settings()
        color_palettes = themer_settings['COLOR_PALETTES']

        # Define the path to the output JS file
        js_file_path = os.path.join(
            themer_path,
            '__themer.js',
        )

        # Write the color palettes to a JS file
        with open(js_file_path, 'w') as js_file:
            js_file.write(self.js_file_warning)
            js_file.write('module.exports = ')
            js_file.write(json.dumps(color_palettes, indent=4))
            js_file.write(';\n')
        
        self.stdout.write(self.style.SUCCESS('Successfully exported color palettes to {}'.format(js_file_path)))
